import type { CasefileData } from './types.js';

function safeJson(value: unknown): string {
  return JSON.stringify(value).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
}

export function renderCasefile(data: CasefileData): string {
  return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${escapeHtml(data.title)}</title><style>
:root{--bg:#071b2b;--panel:#0b2639;--line:#28566a;--text:#f3eddc;--muted:#a8c2cc;--accent:#64d8e8;--ink:#05212c;--bad:#ff755f;--good:#8ed3a6;--warn:#f1c46b;font:16px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--text);background:var(--bg)}*{box-sizing:border-box}body{margin:0;background-color:var(--bg);background-image:linear-gradient(#12364a 1px,transparent 1px),linear-gradient(90deg,#12364a 1px,transparent 1px);background-size:32px 32px}a{color:var(--accent)}.skip{position:absolute;top:-60px;left:12px;background:var(--accent);color:var(--ink);padding:12px;z-index:2}.skip:focus{top:12px}header,main,footer{width:min(1120px,calc(100% - 32px));margin:auto}header{padding:40px 0 24px;border-bottom:1px solid var(--line)}h1{font:700 clamp(2rem,6vw,4rem)/1 system-ui,sans-serif;margin:0 0 12px;letter-spacing:-.04em}.eyebrow{color:var(--accent);text-transform:uppercase;letter-spacing:.14em;font-size:.75rem}.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:1px;background:var(--line);border:1px solid var(--line);margin:24px 0}.stat{padding:16px;background:var(--panel)}.stat b{display:block;color:var(--accent);font-size:1.5rem}.toolbar{display:flex;gap:12px;align-items:end;flex-wrap:wrap;margin:32px 0}label{display:grid;gap:4px;color:var(--muted)}select,input{min-height:44px;background:var(--panel);color:var(--text);border:1px solid var(--line);padding:8px 12px;font:inherit}button:focus-visible,a:focus-visible,select:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid var(--text);outline-offset:3px}.cluster{background:var(--panel);border-left:4px solid var(--bad);padding:20px;margin:0 0 16px;content-visibility:auto}.cluster h2{margin:0;font:700 1.25rem system-ui,sans-serif}.meta{color:var(--muted);font-size:.875rem}.signature{white-space:pre-wrap;overflow-wrap:anywhere;border:1px dashed var(--line);padding:12px}.attempt{border-top:1px solid var(--line);padding:12px 0}summary{min-height:44px;display:flex;align-items:center;cursor:pointer;color:var(--accent)}.divergence{border-left:3px solid var(--warn);padding-left:12px}.status{font-weight:700}.status-passed{color:var(--good)}.status-failed,.status-timedOut{color:var(--bad)}.shot{max-width:100%;height:auto;border:1px solid var(--line)}.empty{border:1px dashed var(--line);padding:32px;text-align:center}.privacy{color:var(--muted);font-size:.875rem}footer{padding:48px 0}@media(max-width:680px){.summary{grid-template-columns:repeat(2,1fr)}header{padding-top:28px}.cluster{padding:16px}}@media(prefers-reduced-motion:no-preference){.cluster{animation:in .24s ease both}@keyframes in{from{opacity:0;transform:translateY(8px)}}}
</style></head><body><a class="skip" href="#main">Skip to casefile</a><header><div class="eyebrow">FC / static incident record</div><h1>${escapeHtml(data.title)}</h1><p>Retries grouped by normalized failure signature. Generated ${escapeHtml(data.generatedAt)}.</p><div class="summary"><div class="stat"><b>${data.summary.tests}</b>tests</div><div class="stat"><b>${data.summary.attempts}</b>attempts</div><div class="stat"><b>${data.summary.failures}</b>failures</div><div class="stat"><b>${data.summary.flaky}</b>flaky</div><div class="stat"><b>${data.summary.clusters}</b>signatures</div></div></header><main id="main"><div class="toolbar"><label>Filter evidence<input id="query" type="search" autocomplete="off" placeholder="Title, project, signature"></label><label>Symptom<select id="symptom"><option value="">All symptoms</option>${[...new Set(data.clusters.map((item) => item.symptom))].map((item) => `<option>${escapeHtml(item)}</option>`).join('')}</select></label></div><p id="count" class="meta" aria-live="polite"></p><section id="clusters" aria-label="Failure clusters"></section></main><footer><p class="privacy">Local static file · no telemetry · traces ${data.privacy.tracesIncluded ? 'included' : 'excluded'} · ${data.privacy.screenshotMasks} screenshot mask${data.privacy.screenshotMasks === 1 ? '' : 's'} configured.</p></footer><script type="application/json" id="casefile-data">${safeJson(data)}</script><script>
const data=JSON.parse(document.querySelector('#casefile-data').textContent);const root=document.querySelector('#clusters');const count=document.querySelector('#count');const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function eventText(e){if(!e)return'No event';return [e.kind,e.method,e.status,e.label,e.url,e.message].filter(Boolean).join(' · ')}
function draw(){const q=document.querySelector('#query').value.toLowerCase();const symptom=document.querySelector('#symptom').value;const rows=data.clusters.filter(c=>(!symptom||c.symptom===symptom)&&(!q||JSON.stringify(c).toLowerCase().includes(q)||c.attempts.some(id=>JSON.stringify(data.attempts.find(a=>a.id===id)).toLowerCase().includes(q))));count.textContent=rows.length+' of '+data.clusters.length+' signatures shown';root.innerHTML=rows.map(c=>{const attempts=c.attempts.map(id=>data.attempts.find(a=>a.id===id)).filter(Boolean);return '<article class="cluster"><div class="meta">'+esc(c.id)+' / '+esc(c.symptom)+' / '+c.count+' occurrence'+(c.count===1?'':'s')+'</div><h2>'+esc(attempts[0]?.title||'Unknown test')+'</h2><p class="signature">'+esc(c.signature)+'</p>'+attempts.map((a,index)=>'<details class="attempt"'+(index===0?' open':'')+'><summary>Retry '+a.retry+' · <span class="status status-'+esc(a.status)+'">'+esc(a.status)+'</span> · '+a.durationMs+' ms</summary>'+(a.divergence?'<p class="divergence"><strong>'+esc(a.divergence.summary)+'</strong><br>Baseline: '+esc(eventText(a.divergence.expected))+'<br>This retry: '+esc(eventText(a.divergence.actual))+'</p>':'')+(a.attachments.length?'<ul>'+a.attachments.map(x=>'<li>'+esc(x.name)+' — '+esc(x.state)+(x.path&&x.contentType.startsWith('image/')?'<br><img class="shot" loading="lazy" alt="Masked failure screenshot '+esc(x.name)+'" src="'+encodeURI(x.path)+'">':'')+(x.note?' ('+esc(x.note)+')':'')+'</li>').join('')+'</ul>':'<p class="meta">No exported attachments.</p>')+'</details>').join('')+'</article>'}).join('')||'<div class="empty"><h2>No matching evidence</h2><p>Clear the filters to return to the full casefile.</p></div>'}
document.querySelector('#query').addEventListener('input',draw);document.querySelector('#symptom').addEventListener('change',draw);draw();
</script></body></html>`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!);
}
